[package]
name = "alloc"
version = "0.1.0"
authors = ["Patrick Lam <patrick.lam@uwaterloo.ca>"]
edition = "2018"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
